Changes for Kitura-Bench to use public git repo of Kitura-Benchmarks
IBM-Swift/Kitura-Benchmarks pull request #1
Opened 2018-08-28 03:17 UTC by mamabusi

2018-09-07 15:38 UTC, djones6 requested changes
I think it's only the 'Location of this script' fix required here (I also tripped over this while implementing #3, but I'm happy to merge this one and rebase mine).

I don't think we want to update the minimum package minor/patch levels (unless I've missed something), because there's nothing in the benchmarks that requires the newer versions, and SPM should pick the latest available versions anyway.

2018-09-07 15:38 UTC, djones6 commented on Bench-Kitura-Blog/build.sh
> +dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
Nit-pick ... blank line was deleted

2018-09-07 15:38 UTC, djones6 commented on Bench-Kitura-Core/latest/Package.swift
> +        .package(url: "https://github.com/IBM-Swift/Kitura.git", from: "2.4.0"),
Do you think that changing the minimum minor/patch versions is necessary?  For example, there's nothing in these benchmarks (yet) that would require Kitura 2.4, they would compile fine on 2.2 or 2.3.  I'd prefer to update these if and when we introduce benchmarks that use the new APIs.

2018-09-10 06:36 UTC, mamabusi commented
@djones6 I have made the requested changes. 
I am fine with you taking the call on whether to put this fix as part of the #3 or merging it as a separate PR. This change would be required for my other PR on Kitura-Bench. Thank you.

2018-09-10 08:25 UTC, djones6 approved these changes

2018-09-10 08:27 UTC, merged